name: "Setup npm"
description: "Sets up npm with caching and installation"

runs:
  using: composite
  steps:
    - name: Extract versions from .tool-versions
      id: versions
      shell: bash
      run: |
        NODE_VERSION=$(grep 'nodejs' .tool-versions | awk '{print $2}')
        echo "node=$NODE_VERSION" >> $GITHUB_OUTPUT

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.versions.outputs.node }}

    - name: Set npm cache path
      shell: bash
      run: echo "STORE_PATH=$(npm config get cache)" >> $GITHUB_ENV

    - name: Restore npm cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          ${{ env.STORE_PATH }}
          node_modules
        key: ${{ runner.os }}-node-${{ steps.versions.outputs.node }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ steps.versions.outputs.node }}-npm-

    - name: Install dependencies
      shell: bash
      run: npm ci --ignore-scripts
