export enum ClassificationStatus {
	SAFE = "SAFE",
	WARNING = "WARNING",
	HARMFUL = "HARMFUL",
}

export enum ClassificationLabel {
	OK = "OK",
	INFORMATIVE = "INFORMATIVE",
	FRIENDLY = "FRIENDLY",
	OFFENSIVE = "OFFENSIVE",
	SPAM = "SPAM",
	MISLEADING = "MISLEADING",
	SENSITIVE = "SENSITIVE",
	PROFANITY = "PROFANITY",
	HATEFUL = "HATEFUL",
	VIOLENT = "VIOLENT",
	SEXUAL = "SEXUAL",
	SELF_HARM = "SELF_HARM",
	DANGEROUS = "DANGEROUS",
	NSFW = "NSFW",
	AI_GENERATED = "AI_GENERATED",
	UNVERIFIED = "UNVERIFIED",
	LANGUAGE_UNKNOWN = "LANGUAGE_UNKNOWN",
}
